name: bns-crypto-fargate-service
on:
  workflow_dispatch: 
    inputs: 
      env: 
        type: choice 
        description: Make a choice
        options: 
          - dev 
          - qa 
          - stage 
          - prod 
jobs: 
  test-deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2 
        with: 
          token: ${{ secrets.TOKEN_GH }} 
      - name: Set env 
        run: echo ${{ inputs.env }} 
      - name: set env 
        run: | 
          if [[ ${{ inputs.env }} == "dev" ]]; then 
              yq '.on.workflow_dispatch.inputs.env.options = ["dev","qa"]' .github/workflows/test1.yml > final-workflow.yml 
              cp final-workflow.yml .github/workflows/test1.yml 
          elif [[ ${{ inputs.env }} == "qa" ]]; then 
              yq '.on.workflow_dispatch.inputs.env.options = ["dev","qa","stage"]' .github/workflows/test1.yml > final-workflow.yml 
              cp final-workflow.yml .github/workflows/test1.yml 
          elif [[ ${{ inputs.env }} == "stage" ]]; then 
              yq '.on.workflow_dispatch.inputs.env.options = ["dev","qa","stage","prod"]' .github/workflows/test1.yml > final-workflow.yml 
              cp final-workflow.yml .github/workflows/test1.yml 
          elif [[ ${{ inputs.env }} == "prod" ]]; then 
              yq '.on.workflow_dispatch.inputs.env.options = ["dev"]' .github/workflows/test1.yml > final-workflow.yml 
              cp final-workflow.yml .github/workflows/test1.yml fi 
      - name: set git 
        run: | 
          git config --global user.name "naveen" 
          git config --global user.email "naveen@gmail.com" 
      - name: git push 
        run: | 
          git commit -am "set env" 
          git push origin main

